- name: Setup and start inception
  hosts: all

  tasks:
    - name: Install required system packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      become: true
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Ensure Docker service is running
      become: true
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to Docker group
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Reset ssh connection for the new group to take effect
      ansible.builtin.meta: reset_connection

    - name: Copy Inception directory
      ansible.builtin.copy:
        src: inception
        dest: .

    - name: Copy .env file
      ansible.builtin.copy:
        src: .env
        dest: inception

    - name: Create {{ ansible_env.HOME }}/data directory
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ ansible_env.HOME }}/data/wordpress"
        - "{{ ansible_env.HOME }}/data/mariadb"

    # NOTE: community.docker.docker_compose_v2 https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html
    - name: Start docker-compose
      community.docker.docker_compose_v2:
        project_src: ./inception
