# TODO: install docker https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
# TODO: copy file https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
# TODO: community.docker.docker_compose_v2 https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html
