- name: Setup and start inception
  hosts: all

  tasks:
    - name: clean docker compose
      community.docker.docker_compose_v2:
        project_src: ./inception
        state: absent
        remove_volumes: true
        remove_orphans: true

    - name: Delete data directory
      become: true
      ansible.builtin.file:
        path: data
        state: absent

    - name: Copy Inception directory
      ansible.builtin.copy:
        src: inception
        dest: .

    - name: Copy .env file
      ansible.builtin.copy:
        src: .env
        dest: inception

    - name: Create {{ ansible_env.HOME }}/data directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ ansible_env.HOME }}/data/wordpress"
        - "{{ ansible_env.HOME }}/data/mariadb"
        - "{{ ansible_env.HOME }}/data/phpmyadmin"

    - name: start docker compose
      environment:
        HOSTNAME: "{{ inventory_hostname }}"
      community.docker.docker_compose_v2:
        project_src: ./inception
        build: always
        recreate: always
